#https://www.mkdocs.org/user-guide/configuration/#
site_name: JCOIN Core Measures
site_url: https://jcoin-maarc.github.io/JCOIN-Core-Measures
nav:
  - Home: index.md
  - Return to JCOIN Data Commons Documentation: https://jcoin-maarc.github.io/jdc-docs-public/
  - Client Core Measures: clients.md
    # - Baseline: https://mbkranz-jcoin-core-measures-appmain-ah4ety.streamlit.app/table-schema-baseline
    # - Timepoints: https://mbkranz-jcoin-core-measures-appmain-ah4ety.streamlit.app/table-schema-time-points
  - Staff Core Measures: staff.md
    # - Baseline: https://mbkranz-jcoin-core-measures-appmain-ah4ety.streamlit.app/table-schema-staff-baseline
    # - Timepoints: https://mbkranz-jcoin-core-measures-appmain-ah4ety.streamlit.app/table-schema-staff-time-points

  - Source Core Measures PDF: source.md

theme:
  name: material
  palette:
    scheme: jdc
  font:
    text: Source Sans Pro
  logo: assets/heal_logo.png
  features:
    # Disable for now, as it causes problems with links to sections in Safari
    # https://github.com/squidfunk/mkdocs-material/issues/3797
    - navigation.sections
    - toc.integrate
    # - navigation.tabs
    # - navigation.tabs.sticky
  favicon: assets/heal_logo.png
extra_css:
  - stylesheets/extra.css
extra:
  homepage: https://jcoin.datacommons.io/
use_directory_urls: true
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - toc:
      permalink: True
      baselevel: 1
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets:
      url_download: True
plugins:
  - search
  - mkdocs-video:
      is_video: True
  # - mermaid2
  #- offline