name: HEAL VLMD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: ["master"]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Convert to HEAL VLMD
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' 
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install healdata-utils
      - name: Convert and commit files
        run: |
          python heal/convert.py
          git add *.json
          git commit -m "Updated HEAL VLMD"