name: build

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build: 
    name: Build the schemas and related products from source yamls
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' 
      - name: Install dependencies
        run: pip install .
      - name: Build from the schemas
        run: |
          python build.py
      - name: Check for changes (fail if none)
        run: |
          ! git diff --quiet
      - name: Commit and push changes
        run: |
          git config user.name ${{ github.triggering_actor }}
          git config user.email ${{ github.triggering_actor }}@users.noreply.github.com

          git add -r *.json *.xlsx *.csv
          git commit "Build table schemas and related products"
          git push
  docs:
    name: Build and Deploy Documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master branch
        uses: actions/checkout@v3
      - name: Install Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip' 
      - name: Install dependencies
        run: pip install .
      - name: Deploy Github Pages
        run: |
          git config user.name ${{ github.triggering_actor }}
          git config user.email ${{ github.triggering_actor }}@users.noreply.github.com
          git pull
          mkdocs gh-deploy